config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Users
  resources :users, only: [:new, :create, :show]

  # Sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Events
  resources :events, only: [:new, :create, :show, :index]

  # Event Attendance
  resources :event_attendances, only: [:create]

  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :hoster, class_name: 'User'

  has_many :event_attendances, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendances #, source: :attendee

  scope :past, -> { where('event_datetime <= ?', DateTime.now) }
  scope :upcoming, -> { where('event_datetime > ?', DateTime.now) }
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'

  validates :attendee_id, uniqueness: { scope: :attended_event_id, message: 'already registered for this event' }

  enum status: [:invited, :accepted]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :hosted_events, foreign_key: :hoster_id, class_name: 'Event'
  has_many :event_attendances, foreign_key: :attendee_id
  has_many :attended_events, through: :event_attendances #, source: :attended_event

  has_many :upcoming_events, -> { where('event_datetime > ?', DateTime.now) },
    through: :event_attendances, source: :attended_event
  has_many :previous_events, -> { where('event_datetime <= ?', DateTime.now) },
    through: :event_attendances, source: :attended_event

  # def upcoming_events
  #   attended_events.where 'event_datetime > ?', DateTime.now
  # end

  # def previous_events
  #   attended_events.where 'event_datetime < ?', DateTime.now
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    User.find(session[:id])
  end

  def logged_in?
    !session[:id].nil? && User.exists?(id: session[:id])
  end

  helper_method :logged_in?
  helper_method :current_user

  def authenticate_user!
    unless logged_in?
      flash[:error] = "You must log in to proceed!"
      redirect_to login_path
    end
  end
end

app/controllers/event_attendances_controller.rb
class EventAttendancesController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    event = Event.find_by_id(params[:event_id])

    if event.nil?
      flash[:alert] = 'Cannot find this event'
      redirect_to events_path
    else
      @ea = EventAttendance.new(attendee: current_user, attended_event_id: params[:event_id])

      if @ea.save
        flash[:notice] = "Successfully registered for this event!"
        redirect_to event
      else
        flash[:alert] = 'Cannot register for this event'
        redirect_to event
      end
    end
  end

  private

  def event_attendance_params
    params
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @event = current_user.hosted_events.build(event_params)

    if @event.save
      redirect_to current_user
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def index
    @events = Event.all
  end

  private

  def event_params
    params.require(:event).permit(:description, :event_datetime, :location)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user
  end

  def create
    @user = User.find_by_username(params[:username])

    if @user.nil?
      flash.now[:alert] = "cannot find user with ID #{params[:username]}"
      render :new
    else
      session['id'] = @user.id
      redirect_to @user
    end
  end

  def destroy
    session.delete(:id)
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to(user_path(@user))
    else
      render :new
    end
  end

  def show
    @user = User.includes(:attended_events, :hosted_events).find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendances_helper.rb
module EventAttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<div class="event">
  <h4><%= event.event_datetime %>, <%= event.location %><h4>
  <p><%= event.description %></p>
  <p>Hosted by: <%= link_to event.hoster.username, event.hoster %></p>
</div>

app/views/events/_event_small.html.erb
<div class="event">
  <p>
    <%= link_to "#{event.event_datetime}, #{event.location}", event %>
  </p>
</div>

app/views/events/index.html.erb
<h1>UPCOMING EVENTS</h1>
<div>
  <%= render partial: 'events/event_small', collection: @events.upcoming, as: :event %>
</div>

<h1>PAST EVENTS</h1>
<div>
  <%= render partial: 'events/event_small', collection: @events.past, as: :event %>
</div>

app/views/events/new.html.erb
<%= form_with model: @event do |f| %>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :location %>
    <%= f.text_field :location %>
  </p>

  <p>
    <%= f.label :event_datetime %>
    <%= f.datetime_field :event_datetime %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/events/show.html.erb
<h1>EVENT</h1>
<div class="event">
  <h4><%= @event.event_datetime %>, <%= @event.location %></h4>
  <p><%= @event.description %></p>
  <p>Hosted by: <%= link_to @event.hoster.username, @event.hoster %></p>
</div>

<p>
  <% if logged_in? %>
    <% if EventAttendance.find_by(attendee: current_user, attended_event: @event) %>
      <p>Already registered for this event!</p>
    <% else %>
      <%= link_to 'Attend', event_attendances_path(event_id: @event.id), method: :create %>
    <% end %>
  <% else %>
    <%= link_to 'Log in', login_path %> to attend on this event!
  <% end %>
</p>

<h1>ATTENDEES</h1>
<div>
  <ul>
    <% @event.attendees.each do |attendee| %>
      <li>
        <%= attendee.username %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="notice"><p><%= notice %></p></div>
    <div class="alert"><p><%= alert %></p></div>

    <div>
      <ul>
        <% if logged_in? %>
          <li>Logged in as <%= link_to current_user.username, current_user %></li>
          <li><%= link_to 'Host new event', new_event_path %></li>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
        <% else %>
          <li>Not logged in</li>
          <li><%= link_to 'Log in', login_path %> / <%= link_to 'Sign up', new_user_path %></li>
        <% end %>

        <li><%= link_to 'Events', events_path %></li>
      </ul>
    </div>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>REGISTER NEW USER</h1>
... or <%= link_to 'Log in', login_path %>

<%= form_with model: @user do |f| %>
  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/show.html.erb
<h1>USER INFO</h1>
<p>Username: <%= @user.username %></p>
<p>ID: <%= @user.id %></p>

byebug

<h1>UPCOMING EVENTS</h1>
<% if @user.upcoming_events.any? %>
  <%= render partial: 'events/event_small', collection: @user.upcoming_events, as: :event %>
<% else %>
  <p>This used doesn't attend to any upcoming event yet :(</p>
<% end %>

<h1>PREVIOUSLY ATTENDED EVENTS</h1>
<% if @user.previous_events.any? %>
  <%= render partial: 'events/event_small', collection: @user.previous_events, as: :event %>
<% else %>
  <p>This used didn't attend at any event yet :(</p>
<% end %>

<h1>HOSTED EVENTS</h1>
<% if @user.hosted_events.any? %>
  <%= render partial: 'events/event_small', collection: @user.hosted_events, as: :event %>
<% else %>
  <p>This used didn't host any event yet :(</p>
<% end %>